version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: |
            echo Hello, world.
            echo $CIRCLE_BRANCH
            echo $CIRCLE_COMPARE_URL
            echo $CIRCLE_PULL_REQUEST
            echo $CIRCLE_PR_NUMBE
            git diff --name-only HEAD^

      - run:
          name: Print the Current Time
          command: date
