version: 2
jobs:
  build:
    docker:
      - image: dancinllama/dockerdx
    branches:
      only:
       - master
    steps:
      - checkout
      - run:
          name: Greeting
          command: |
            echo Hello, world.
            echo ${CIRCLE_BRANCH}
            echo ${CIRCLE_COMPARE_URL}
            echo ${CIRCLE_PULL_REQUEST}
            echo ${CIRCLE_PR_NUMBER}
            git log --merges --first-parent -n 2 | grep commit | sed 's/commit //g' | tr '\n' ' ' | xargs | sed 's/ /../g' | xargs git diff --name-only > tmp/diffs
            echo tmp/diffs

      - run:
          name: Print the Current Time
          command: date
