version: 2
jobs:
  build:
    docker:
      - image: dancinllama/dockerdx
    steps:
      - checkout
      - run:
          name: Greeting
          command: |
            mkdir -p tmp/force-app/main/default/staticresources
            git diff --name-only HEAD^ > tmp/diffs

            find force-app/main/default/staticresources -mindepth 1 -name bundle* | xargs -n1 dirname > targets
            cat targets | while read line
            do
              mv -n -t tmp/force-app/main/default/staticresources $line $line.resource-meta.xml
            done

            cd tmp
            cat diffs | while read line
            do
              if [[ $line =~ bundle ]];
              then
                echo $line
                export base=`dirname $line`
                echo $base
                cp -r $base ../force-app/main/default/staticresources/
                cp ${base}.resource-meta.xml ../force-app/main/default/staticresources/
              fi
            done
            cd ..
            ls -R force-app/
            sfdx force:source:convert -d metadata
