version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:curl-browsers-legacy
    steps:
      - checkout
      - run:
          name: Greeting
          command: |
            echo Hello, world.
            echo $CIRCLE_BRANCH
            echo $CIRCLE_COMPARE_URL
            echo $CIRCLE_PULL_REQUEST
            echo $CIRCLE_PR_NUMBE
            mkdir -p tmp/force-app/main/default/
            mv force-app/main/default/staticresources tmp/force-app/main/default/
            cd tmp
            git diff --name-only HEAD^ | while read line
            do
              echo $line
              if [[ $line =~ staticresources ]];
              then
                mv -p $line ../force-app/main/default/staticresources/
              fi
            done
            ls -R force-app/
