version: 2
jobs:
  build:
    docker:
      - image: dancinllama/dockerdx
    steps:
      - checkout
      - run:
          name: Greeting
          command: |
            mkdir -p tmp/force-app/main/default/
            git diff --name-only HEAD^ > tmp/diffs
            mv force-app/main/default/staticresources tmp/force-app/main/default/
            mkdir -p force-app/main/default/staticresources
            cd tmp
            cat diffs | while read line
            do
              if [[ $line =~ bundle ]];
              then
                echo $line
                export base=`dirname $line`
                echo $base
                cp -r $base ../force-app/main/default/staticresources/
                cp ${base}.resource-meta.xml ../force-app/main/default/staticresources/
              fi
            done
            cd ..
            ls -R force-app/
            sfdx force:source:convert -d metadata
